# Generated by Django 4.0.4 on 2023-10-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companymodel',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='extracts',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='transform',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='objectitem',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='productchain',
            name='polymorphic_ctype',
        ),
    ]
