# Generated by Django 4.2.6 on 2023-10-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectitem',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='objectitem',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='objectitem',
            name='category',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='objectitem',
            name='supplier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='objectitem',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='storageType',
            field=models.CharField(blank=True, choices=[('WRH', 'Warehouse'), ('RWH', 'Refrigerated Warehouse'), ('HWH', 'Heated Warehouse')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
