# Generated by Django 4.0.4 on 2023-10-25 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0002_alter_companymodel_options_alter_extracts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productchain',
            name='lastStep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastStep', to='databaseModels.companymodel'),
        ),
        migrations.AlterField(
            model_name='productchain',
            name='nextStep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextStep', to='databaseModels.companymodel'),
        ),
    ]
