# Generated by Django 4.2.6 on 2023-10-24 07:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0002_alter_objectitem_id_alter_productchain_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extracts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('impact_score', models.IntegerField(blank=True, null=True)),
                ('departure', models.DateTimeField()),
                ('extract_type', models.CharField(choices=[('MIN', 'Mining'), ('CHO', 'Chopping'), ('CHE', 'Chemical Creation')], max_length=3)),
                ('objectItem_output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extr_output', to='databaseModels.objectitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
