# Generated by Django 4.2.6 on 2023-10-26 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0003_alter_productchain_laststep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productchain',
            name='industry_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='industry_step', to='databaseModels.companymodel'),
        ),
        migrations.AlterField(
            model_name='productchain',
            name='currStep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currStepFK', to='databaseModels.productchain'),
        ),
        migrations.AlterField(
            model_name='productchain',
            name='lastStep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastStepFK', to='databaseModels.productchain'),
        ),
        migrations.AlterField(
            model_name='productchain',
            name='nextStep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextStepFK', to='databaseModels.productchain'),
        ),
    ]
