# Generated by Django 4.2.6 on 2023-10-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0004_productchain_industry_step_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productchain',
            old_name='object',
            new_name='objectItem',
        ),
    ]
