# Generated by Django 4.2.6 on 2023-10-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0005_rename_object_productchain_objectitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productchain',
            name='currStep',
        ),
    ]
